# https://www.youtube.com/watch?v=k8H0KCtsTR8&ab_channel=DataKnox 

# Or any preferred Python version.
FROM python:3.11

# ADD docs .
# COPY requirements.txt requirements.txt
# RUN pip3 install -r requirements.txt

# Or enter the name of your unique directory and parameter set.
# You can add "./docs" as second parameter
CMD ["python3"]   

# After building Docker image
# Run in Git terminal => docker run -d -i --name name-of-container name-of-img bash